name: Upcoming NFL Schedule → Fourth Down

on:
  schedule:
    # Every Wednesday at 15:00 UTC (10:00 CT during CST, 10/09/… adjust as desired)
    - cron: "0 15 * * 3"
  workflow_dispatch: {}

jobs:
  build-schedule:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Setup R deps
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::readr
            any::jsonlite
            any::lubridate
            any::stringr
            any::glue
            any::nflreadr

      - name: Fetch upcoming schedule
        id: schedule
        env:
          SCHEDULE_OUT_DIR: artifacts
        run: |
          Rscript R/bots/fetch_upcoming_schedule.R

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: upcoming-schedule
          path: artifacts/*

  run-fourth-down-checker:
    needs: build-schedule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download schedule artifact
        uses: actions/download-artifact@v4
        with:
          name: upcoming-schedule
          path: artifacts

      - name: Show schedule summary
        run: |
          echo "CSV:"
          cat artifacts/upcoming_week_schedule.csv || true
          echo "JSON:"
          cat artifacts/upcoming_week_game_ids.json || true

      # Build a matrix of game_ids dynamically (skip if empty)
      - name: Prepare matrix
        id: prep
        run: |
          if [ -s artifacts/upcoming_week_game_ids.json ]; then
            ids=$(jq -r '.game_ids' artifacts/upcoming_week_game_ids.json)
            # default to empty list if null
            echo "matrix={\"game_id_list\":${ids:-[]}}" >> $GITHUB_OUTPUT
          else
            echo 'matrix={"game_id_list":[]}' >> $GITHUB_OUTPUT
          fi

      - name: Run checker (all games)
        if: ${{ fromJson(steps.prep.outputs.matrix).game_id_list != '' && join(fromJson(steps.prep.outputs.matrix).game_id_list) != '' }}
        run: |
          jq -r '.game_ids[]?' artifacts/upcoming_week_game_ids.json | while read -r GAME_ID; do
            echo ">>> Running fourth-down checker for ${GAME_ID}"
            # Example hook — replace with your actual command/script:
            # Rscript R/bots/run_fd_weekly.R --game-id "${GAME_ID}"
            # Or if you have a live-checker chunker:
            # Rscript -e "source('R/bots/run_fd_live_once.R'); run_fd_live_once(game_id='${GAME_ID}')"
            echo "Completed ${GAME_ID}"
          done

      - name: No games to process
        if: ${{ !(fromJson(steps.prep.outputs.matrix).game_id_list != '' && join(fromJson(steps.prep.outputs.matrix).game_id_list) != '') }}
        run: echo "No upcoming games in window. Exiting successfully."
